#!/bin/bash
#
# You can check if there is a new release at https://www.python.org/downloads/
#
# After python is installed, you can update the default pip and setuptools
#
#       python3 -m pip install --upgrade pip setuptools
#

set -e

cd "$(mktemp -d)"

sudo apt-get install -y gcc make libreadline-dev libssl-dev

wget https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tar.xz
openssl md5 Python-3.5.2.tar.xz | grep 8906efbacfcdc7c3c9198aeefafd159e

tar xf Python-3.5.2.tar.xz
cd Python-3.5.2

./configure --prefix="$HOME/local"
make -j 8
make install
