#!/bin/bash

set -e

cd "$(mktemp -d)"

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg --install google-chrome-stable_current_amd64.deb
sudo apt-get install --assume-yes --fix-broken
