#!/bin/bash

test "${BASH_SOURCE[0]}" = "$0" || {
    echo "Error: '${BASH_SOURCE[0]}' should not be sourced"
    return 1
}

set -o pipefail         # proper status code for a pipeline
set -o errexit          # -e exit when seeing a nonzero status code
set -o nounset          # -u using unbound variable is an error
shopt -s failglob       # pathname expansion failing is an error

__my_exit_trap__ () {
    local LAST_STATUS=$? LAST_COMMAND="$BASH_COMMAND"
    if [[ $LAST_STATUS != 0 ]]
    then
        printf '\nCommand `%s` has nonzero exit status.\n\n' "$LAST_COMMAND"
    fi
}
trap __my_exit_trap__ EXIT

##############################################################################

# make sure we are executing this bash script on the expected machine

grep -q 'Ubuntu 16.04' /etc/issue
test -e /sys/class/net/enp8s0
grep -q '3c:a8:2a:7f:b2:9d' /sys/class/net/enp8s0/address

##############################################################################

# set up the network interface for sharing Internet connectivity

echo > /etc/network/interfaces '
auto lo
auto enp8s0
iface lo inet loopback
iface enp8s0 inet static
  address 172.25.0.1/24
'

ifdown enp8s0
ifup enp8s0

##############################################################################

# set up NAT

echo > /etc/sysctl.conf 'net.ipv4.ip_forward=1'

sysctl -p

[[ "$(< /proc/sys/net/ipv4/ip_forward )" == 1 ]]

if ! dpkg -s iptables-persistent &> /dev/null; then
  debconf-set-selections <<<'iptables-persistent iptables-persistent/autosave_v4 boolean true'
  debconf-set-selections <<<'iptables-persistent iptables-persistent/autosave_v6 boolean true'
  apt-get install -y iptables-persistent
fi

iptables -t nat -F
iptables -t nat -A POSTROUTING ! -o enp8s0 -j MASQUERADE

service netfilter-persistent save

##############################################################################

# set up a DHCP server

if ! dpkg -s isc-dhcp-server &> /dev/null; then
  apt-get install -y isc-dhcp-server
fi

echo > /etc/default/isc-dhcp-server 'INTERFACES="enp8s0"'

echo > /etc/dhcp/dhcpd.conf '
default-lease-time 600;
max-lease-time 7200;
option domain-name-servers 8.8.8.8, 8.8.4.4;
subnet 172.25.0.0 netmask 255.255.255.0 {
  range 172.25.0.10 172.25.0.254;
  option routers 172.25.0.1;
  host fabiafx5625a {
    hardware ethernet 53:ae:74:96:89:0a;
    fixed-address 172.25.0.2;
  }
}
'

service isc-dhcp-server restart
