#!/bin/bash

set -e

test -n "$BASH_VERSION"
grep -q 'Ubuntu 14.04' /etc/issue
test "$(uname -m)" = x86_64
test "$(id -u)" = 0
wget -q -O /dev/null https://duckduckgo.com/

BACKUPSUFFIX=$(date +.bak.%Y%m%d.%H%M%S)

##############################################################################

echo Asia/Taipei > /etc/timezone
dpkg-reconfigure --frontend=noninteractive tzdata

##############################################################################

cp /etc/apt/sources.list{,"$BACKUPSUFFIX"}

# MIRROR=http://archive.ubuntu.com/ubuntu/
# MIRROR=http://mirrors.digitalocean.com/ubuntu/
# MIRROR=http://mirrors.linode.com/ubuntu/
# MIRROR=http://security.ubuntu.com/ubuntu/
# MIRROR=http://tw.archive.ubuntu.com/ubuntu/
# MIRROR=http://us.archive.ubuntu.com/ubuntu/
MIRROR=http://free.nchc.org.tw/ubuntu/

echo "
deb $MIRROR trusty           main restricted universe multiverse
deb $MIRROR trusty-updates   main restricted universe multiverse
deb $MIRROR trusty-backports main restricted universe multiverse
deb $MIRROR trusty-security  main restricted universe multiverse
" > /etc/apt/sources.list

##############################################################################

cp /etc/apt/apt.conf.d/{10periodic,.10periodic"$BACKUPSUFFIX"}
echo '
APT::Periodic::Enable "0";
APT::Periodic::Unattended-Upgrade "0";
APT::Periodic::Update-Package-Lists "0";
APT::Periodic::Download-Upgradeable-Packages "0";
APT::Periodic::AutocleanInterval "0";
' > /etc/apt/apt.conf.d/10periodic

##############################################################################

apt-get update
apt-get dist-upgrade -y
apt-get autoremove -y
apt-get install -y build-essential exuberant-ctags gdb git gnupg2 htop mosh openssh-server screen tig tmux valgrind vim

##############################################################################

cp /etc/vim/vimrc{,"$BACKUPSUFFIX"}
echo > /etc/vim/vimrc 'se nocp uc=0 vi= nolpl mls=0 noml hid sc shm+=I bs=2 et ai ci pi sw=4 sts=4 fo=qn tw=78 hls cpt=.,w,b,u|nn K <Nop>'
update-alternatives --set editor /usr/bin/vim.basic
printf "\
export VISUAL=/usr/bin/vim.basic
export EDITOR=/usr/bin/vim.basic
export SELECTED_EDITOR=/usr/bin/vim.basic
" > /etc/profile.d/just_let_me_use_vim_please.sh

##############################################################################

cp /etc/ssh/sshd_config{,"$BACKUPSUFFIX"}
sed -i 's@^PermitRootLogin.*$@PermitRootLogin yes@' /etc/ssh/sshd_config
if ! grep -q 'UseDNS' /etc/ssh/sshd_config
then
    echo 'UseDNS no' >> /etc/ssh/sshd_config
fi
service ssh restart

##############################################################################

cp /etc/default/keyboard{,"$BACKUPSUFFIX"}
sed -i 's@^XKBOPTIONS=.*$@XKBOPTIONS="ctrl:nocaps"@' /etc/default/keyboard
dpkg-reconfigure --priority=high keyboard-configuration

##############################################################################

if grep -q '^#includedir /etc/sudoers.d$' /etc/sudoers; then
    echo 'Let any user in "sudo" group do anything without a password prompt'
    echo '%sudo ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/easysudo
    chmod 0440 /etc/sudoers.d/*
fi
