#!/bin/bash

set -e

[[ $( cat /etc/issue ) = 'Ubuntu 14.04'* ]] || { echo 'Error: This is not Ubuntu 14.04.'; false; }
[[ $( id -u ) = 0 ]] || { echo 'Error: You are not root.'; false; }
printf %s 'Testing network connectivity... ' &&
ping -q -c 6 -i 0.2 -W 2 8.8.8.8 &> /dev/null &&
ping -q -c 6 -i 0.2 -W 2 ntp.ubuntu.com &> /dev/null &&
ping -q -c 6 -i 0.2 -W 2 free.nchc.org.tw &> /dev/null &&
echo OK || { echo FAIL; false; }


# http://archive.ubuntu.com/ubuntu/
# http://free.nchc.org.tw/ubuntu/
# http://mirrors.digitalocean.com/ubuntu/
# http://mirrors.linode.com/ubuntu/
# http://security.ubuntu.com/ubuntu/
# http://tw.archive.ubuntu.com/ubuntu/
# http://us.archive.ubuntu.com/ubuntu/
mv /etc/apt/sources.list /etc/apt/sources.list.backup."$(date +%Y%m%d.%H%M%S)"
echo > /etc/apt/sources.list '
deb     http://free.nchc.org.tw/ubuntu/ trusty           main restricted universe multiverse
deb-src http://free.nchc.org.tw/ubuntu/ trusty           main restricted universe multiverse
deb     http://free.nchc.org.tw/ubuntu/ trusty-updates   main restricted universe multiverse
deb-src http://free.nchc.org.tw/ubuntu/ trusty-updates   main restricted universe multiverse
deb     http://free.nchc.org.tw/ubuntu/ trusty-backports main restricted universe multiverse
deb-src http://free.nchc.org.tw/ubuntu/ trusty-backports main restricted universe multiverse
deb     http://free.nchc.org.tw/ubuntu/ trusty-security  main restricted universe multiverse
deb-src http://free.nchc.org.tw/ubuntu/ trusty-security  main restricted universe multiverse
'
apt-get update


echo Asia/Taipei > /etc/timezone
dpkg-reconfigure --frontend=noninteractive tzdata
ntpdate -u ntp.ubuntu.com


apt-get dist-upgrade --assume-yes


apt-get install --assume-yes openssh-server mosh vim git tmux screen build-essential


mv /etc/vim/vimrc /etc/vim/vimrc.backup."$(date +%Y%m%d.%H%M%S)"
echo > /etc/vim/vimrc 'se nocp uc=0 vi= nolpl rtp=$VIMRUNTIME mls=0 hid bs=2 ai ci pi et sts=4 sw=4 kp=:help fo=qn tw=79 sc shm+=I lcs=tab:>-,trail:.|sy off|filet off'
update-alternatives --set editor /usr/bin/vim.basic


cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup."$(date +%Y%m%d.%H%M%S)"
sed --in-place 's@^PermitRootLogin without-password$@PermitRootLogin yes@' /etc/ssh/sshd_config
if ! grep -q 'UseDNS' /etc/ssh/sshd_config; then echo 'UseDNS no' >> /etc/ssh/sshd_config; fi
service ssh restart



if dpkg -l ubuntu-desktop &> /dev/null; then

  sed --in-place=".backup.$(date +%Y%m%d.%H%M%S)" 's@^XKBOPTIONS=.*$@XKBOPTIONS="ctrl:nocaps"@' /etc/default/keyboard
  dpkg-reconfigure --priority=high keyboard-configuration


  echo manual > /etc/init/lightdm.override


  cp /etc/default/grub /etc/default/grub.backup."$(date +%Y%m%d.%H%M%S)"
  sed --in-place 's@^GRUB_HIDDEN_TIMEOUT=0$@#GRUB_HIDDEN_TIMEOUT=0@' /etc/default/grub
  sed --in-place 's@^GRUB_TIMEOUT=10$@GRUB_TIMEOUT=2@' /etc/default/grub
  sed --in-place 's@^GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"$@GRUB_CMDLINE_LINUX_DEFAULT=""@' /etc/default/grub
  update-grub

fi
