#!/bin/bash
#
# sudo su -
# wget -P /tmp https://github.com/concise/dry/raw/master/ubuntu-python3
# bash /tmp/ubuntu-python3
#

set -e

apt-get install -y make libreadline-dev libssl-dev
wget -P /tmp https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tar.xz
openssl dgst -md5 /tmp/Python-3.5.1.tar.xz | grep e9ea6f2623fffcdd871b7b19113fde80
rm -rf /tmp/Python-3.5.1
tar xJf /tmp/Python-3.5.1.tar.xz -C /tmp
cd /tmp/Python-3.5.1
./configure
make -j 8
make install
pip3 install --upgrade pip setuptools virtualenv
