#!/bin/bash
#
# sudo su -
# wget -O /tmp/ubuntu https://github.com/concise/dry/raw/master/ubuntu
# bash /tmp/ubuntu
#

set -e

[[ $( cat /etc/issue ) = 'Ubuntu 14.04'* ]] ||
{ echo 'Error: This is not Ubuntu 14.04.'; false; }

test 0 = "$( id -u )" || { echo 'Error: You are not root.'; false; }

printf %s 'Testing network connectivity... ' &&
ping -q -c 6 -i 0.2 -W 2 8.8.8.8 &> /dev/null &&
ping -q -c 6 -i 0.2 -W 2 ntp.ubuntu.com &> /dev/null &&
ping -q -c 6 -i 0.2 -W 2 mirror01.idc.hinet.net &> /dev/null &&
echo OK || { echo FAIL; false; }

echo Asia/Taipei > /etc/timezone
dpkg-reconfigure --frontend=noninteractive tzdata
ntpdate -u ntp.ubuntu.com
echo
echo 'System time updated.'
echo

sed --in-place=".backup.$(date +%Y%m%d.%H%M%S)" 's@//.*archive.ubuntu.com/@//mirror01.idc.hinet.net/@' /etc/apt/sources.list
apt-get update
apt-get dist-upgrade --assume-yes
apt-get install --assume-yes openssh-server
echo
echo 'System packages updated.'
echo 'OpenSSH server is installed.'
echo

cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup."$(date +%Y%m%d.%H%M%S)"
sed --in-place 's@^PermitRootLogin without-password$@PermitRootLogin yes@' /etc/ssh/sshd_config
if ! grep -q 'UseDNS' /etc/ssh/sshd_config; then echo 'UseDNS no' >> /etc/ssh/sshd_config; fi
service ssh restart
echo
echo 'The root user will be able to login via SSH with password.'
echo 'The stupid reverse DNS lookup for sshd is now disabled.'
echo

mv /etc/vim/vimrc /etc/vim/vimrc.backup."$(date +%Y%m%d.%H%M%S)"
echo > /etc/vim/vimrc 'se nocp uc=0 vi= nolpl rtp=$VIMRUNTIME mls=0 hid bs=2 ai ci pi et sts=4 sw=4 kp=:help fo=qn tw=79 sc shm+=I lcs=tab:>-,trail:.|sy off|filet off'
update-alternatives --set editor /usr/bin/vim.basic
echo
echo '/etc/vim/vimrc is updated.'
echo '/usr/bin/vim.basic is now the default text editor.'
echo
