#!/bin/bash

printf '%s\n%s\n%s\n' '#!/bin/sh -e' '> /dev/uhid' 'chmod 0666 /dev/uhid' > /etc/rc.local
printf '%s\n' 'KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0666"' > /etc/udev/rules.d/99-expose-all-hidraw.rules

udevadm trigger
> /dev/uhid
chmod 0666 /dev/uhid
