#!/bin/bash

set -e

test -n "$BASH_VERSION"
grep -q 'Ubuntu 16.04' /etc/issue
test "$(id -u)" = 0
wget -q -O /dev/null https://duckduckgo.com/

##############################################################################

timedatectl set-timezone Asia/Taipei

##############################################################################

mv /etc/apt/sources.list /etc/apt/sources.list.bak."$(date +%Y%m%d.%H%M%S)"

# MIRROR=http://archive.ubuntu.com/ubuntu/
# MIRROR=http://mirrors.digitalocean.com/ubuntu/
# MIRROR=http://mirrors.linode.com/ubuntu/
# MIRROR=http://security.ubuntu.com/ubuntu/
# MIRROR=http://tw.archive.ubuntu.com/ubuntu/
# MIRROR=http://us.archive.ubuntu.com/ubuntu/
MIRROR=http://free.nchc.org.tw/ubuntu/

echo "
deb $MIRROR xenial           main restricted universe multiverse
deb $MIRROR xenial-updates   main restricted universe multiverse
deb $MIRROR xenial-backports main restricted universe multiverse
deb $MIRROR xenial-security  main restricted universe multiverse
# deb-src $MIRROR xenial           main restricted universe multiverse
# deb-src $MIRROR xenial-updates   main restricted universe multiverse
# deb-src $MIRROR xenial-backports main restricted universe multiverse
# deb-src $MIRROR xenial-security  main restricted universe multiverse
" > /etc/apt/sources.list

##############################################################################

apt update
apt full-upgrade -y
apt autoremove -y
apt install -y build-essential exuberant-ctags gdb git gnupg2 htop mosh openssh-server screen tig tmux valgrind vim python3 python3-dev python3-pip python3-venv

##############################################################################

mv /etc/vim/vimrc /etc/vim/vimrc.bak."$(date +%Y%m%d.%H%M%S)"
echo > /etc/vim/vimrc 'se nocp uc=0 vi= nolpl rtp=$VIMRUNTIME mls=0 hid bs=2 ai ci pi et sts=4 sw=4 kp=:help fo=qn tw=79 sc shm+=I lcs=tab:>-,trail:.|sy off|filet off'
update-alternatives --set editor /usr/bin/vim.basic
echo > /etc/profile.d/my_selected_editor.sh 'export SELECTED_EDITOR=/usr/bin/vim.basic'

##############################################################################

cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak."$(date +%Y%m%d.%H%M%S)"
sed -i 's@^PermitRootLogin.*$@PermitRootLogin yes@' /etc/ssh/sshd_config
if ! grep -q 'UseDNS' /etc/ssh/sshd_config
then
    echo 'UseDNS no' >> /etc/ssh/sshd_config
fi
service ssh restart

##############################################################################

cp /etc/default/keyboard /etc/default/keyboard.bak."$(date +%Y%m%d.%H%M%S)"
sed -i 's@^XKBOPTIONS=.*$@XKBOPTIONS="ctrl:nocaps"@' /etc/default/keyboard
dpkg-reconfigure --priority=high keyboard-configuration
