#!/bin/bash

set -e

test -n "$BASH_VERSION"
grep -q 'Ubuntu 16.04' /etc/issue
test "$(uname -m)" = x86_64
test "$(id -u)" = 0
wget -q -O /dev/null https://duckduckgo.com/

BACKUPSUFFIX=$(date +.bak.%Y%m%d.%H%M%S)

##############################################################################

timedatectl set-timezone Asia/Taipei

##############################################################################

cp /etc/apt/sources.list{,"$BACKUPSUFFIX"}

# MIRROR=http://archive.ubuntu.com/ubuntu/
# MIRROR=http://mirrors.digitalocean.com/ubuntu/
# MIRROR=http://mirrors.linode.com/ubuntu/
# MIRROR=http://security.ubuntu.com/ubuntu/
# MIRROR=http://tw.archive.ubuntu.com/ubuntu/
# MIRROR=http://us.archive.ubuntu.com/ubuntu/
MIRROR=http://free.nchc.org.tw/ubuntu/

echo "
deb $MIRROR xenial           main restricted universe multiverse
deb $MIRROR xenial-updates   main restricted universe multiverse
deb $MIRROR xenial-backports main restricted universe multiverse
deb $MIRROR xenial-security  main restricted universe multiverse
" > /etc/apt/sources.list

##############################################################################

cp /etc/apt/apt.conf.d/{10periodic,.10periodic"$BACKUPSUFFIX"}
echo '
APT::Periodic::Enable "0";
APT::Periodic::Unattended-Upgrade "0";
APT::Periodic::Update-Package-Lists "0";
APT::Periodic::Download-Upgradeable-Packages "0";
APT::Periodic::AutocleanInterval "0";
' > /etc/apt/apt.conf.d/10periodic

##############################################################################

apt update
apt full-upgrade -y
apt autoremove -y
apt install -y build-essential exuberant-ctags gdb git gnupg2 htop mosh openssh-server screen tig tmux valgrind vim

##############################################################################

cp /etc/vim/vimrc{,"$BACKUPSUFFIX"}
echo > /etc/vim/vimrc 'se nocp uc=0 vi= nolpl rtp=$VIMRUNTIME mls=0 hid bs=2 ai ci pi et sts=4 sw=4 kp=:help fo=qn tw=79 sc shm+=I lcs=tab:>-,trail:.|sy off|filet off'
update-alternatives --set editor /usr/bin/vim.basic
printf "\
export VISUAL=/usr/bin/vim.basic
export EDITOR=/usr/bin/vim.basic
export SELECTED_EDITOR=/usr/bin/vim.basic
" > /etc/profile.d/just_let_me_use_vim_please.sh

##############################################################################

cp /etc/ssh/sshd_config{,"$BACKUPSUFFIX"}
sed -i 's@^PermitRootLogin.*$@PermitRootLogin yes@' /etc/ssh/sshd_config
if ! grep -q 'UseDNS' /etc/ssh/sshd_config
then
    echo 'UseDNS no' >> /etc/ssh/sshd_config
fi
service ssh restart

##############################################################################

cp /etc/default/keyboard{,"$BACKUPSUFFIX"}
sed -i 's@^XKBOPTIONS=.*$@XKBOPTIONS="ctrl:nocaps"@' /etc/default/keyboard
dpkg-reconfigure --priority=high keyboard-configuration

##############################################################################

cp /etc/systemd/logind.conf{,"$BACKUPSUFFIX"}
sed -i 's@^#\(HandleLidSwitch\)=.*@\1=ignore@' /etc/systemd/logind.conf

##############################################################################

systemctl set-default multi-user.target

##############################################################################

if grep -q '^#includedir /etc/sudoers.d$' /etc/sudoers; then
    echo 'Let any user in "sudo" group do anything without a password prompt'
    echo '%sudo ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/easysudo
    chmod 0440 /etc/sudoers.d/*
fi
